repos:
#  - repo: https://github.com/pre-commit/mirrors-isort
#    rev: v5.10.1
#    hooks:
#      - id: isort
#
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
#
#  - repo: https://github.com/pre-commit/mirrors-mypy
#    rev: v1.14.1
#    hooks:
#      - id: mypy
#
#  - repo: https://github.com/PyCQA/flake8
#    rev: 7.1.1
#    hooks:
#      - id: flake8
